# from walker_trial_of_different_algorithms import walker_sac_training
from training_code.gymnasium.bipedal_walker import bipedal_walker_SAC
# from training_code.gymnasium.mountain_car_continuous import mountain_car_continuous_SAC
# from training_code.gymnasium.pendulum import pendulum_SAC
# from training_code.gymnasium.cart_pole import cart_pole_DDQN